_base_ = ["wedetect_base_coco_full_tuning_8xbs4_2e-5.py"]

import os


# IMPORTANT:
# This should point to the merged checkpoint generated by:
#   prepare_stage3_init_ckpt.py --replace-text
# It keeps WeDetect pretrained detector weights while replacing text backbone.
load_from = "./work_dirs/stage3_llm2clip/wedetect_stage3_init.pth"


# Replace RoBERTa with LLM2CLIP. Keep output_dim=768 to match WeDetect head.
model = dict(
    backbone=dict(
        text_model=dict(
            _delete_=True,
            type="LLM2CLIPLanguageBackbone",
            model_name="/ssd/wzh/models/LLM2CLIP-Llama-3.2-1B-Instruct-CC-Finetuned",
            output_dim=768,
            adapter_dim=64,
            adapter_dropout=0.0,
            use_adapter=True,
            pooling="eos",
            max_length=77,
            trust_remote_code=True,
            frozen_modules=[],
        ),
    ),
)


# Keep text backbone trainable in stage3, but with a smaller LR on text base model.
optim_wrapper = dict(
    paramwise_cfg=dict(
        custom_keys={
            "backbone.text_model.model": dict(lr_mult=0.1),
            "backbone.text_model": dict(lr_mult=1.0),
            "logit_scale": dict(weight_decay=0.0),
        }
    )
)


# --------------------------
# Multi-dataset training set
# --------------------------
# Converted by `convert_wedetect_datasets_xyxy.sh`.
converted_root = os.path.abspath(
    os.environ.get("WEDETECT_CONVERTED_ROOT", "./data/converted_wedetect_xyxy")
)

o365_data_root = os.environ.get("O365_DATA_ROOT", "/home/wanzhiheng/workspace/mmdetection/data/objects365v1/")
flickr_data_root = os.environ.get("FLICKR_DATA_ROOT", "/ssd/wzh/data/flickr30k_entities/")
gqa_data_root = os.environ.get("GQA_DATA_ROOT", "/ssd/wzh/data/gqa/")
coco_val_data_root = os.environ.get("COCO_VAL_DATA_ROOT", "./data/coco/")
coco_val_ann = os.environ.get("COCO_VAL_ANN", "annotations/instances_val2017.json")
coco_val_class_text_path = os.environ.get("COCO_VAL_CLASS_TEXT", "data/texts/coco_class_texts.json")

o365_class_text_path = os.path.join(converted_root, "o365_class_texts_xyxy.json")
flickr_class_text_path = os.path.join(converted_root, "flickr_class_texts_xyxy.json")
gqa_class_text_path = os.path.join(converted_root, "gqa_class_texts_xyxy.json")
o365_classes_path = os.path.join(converted_root, "o365_classes_xyxy.json")
flickr_classes_path = os.path.join(converted_root, "flickr_classes_xyxy.json")
gqa_classes_path = os.path.join(converted_root, "gqa_classes_xyxy.json")

o365_train_dataset = dict(
    type="MultiModalDataset",
    dataset=dict(
        type="WeCocoDataset",
        data_root=o365_data_root,
        ann_file=os.path.join(converted_root, "o365_train_coco_xyxy.json"),
        data_prefix=dict(img="train/"),
        metainfo=dict(classes=o365_classes_path),
        filter_cfg=dict(filter_empty_gt=False, min_size=32),
    ),
    class_text_path=o365_class_text_path,
    pipeline=_base_.train_pipeline,
)

flickr_train_dataset = dict(
    type="MultiModalDataset",
    dataset=dict(
        type="WeCocoDataset",
        data_root=flickr_data_root,
        ann_file=os.path.join(converted_root, "flickr_train_coco_xyxy.json"),
        data_prefix=dict(img="flickr30k_images/"),
        metainfo=dict(classes=flickr_classes_path),
        filter_cfg=dict(filter_empty_gt=False, min_size=32),
    ),
    class_text_path=flickr_class_text_path,
    pipeline=_base_.train_pipeline,
)

gqa_train_dataset = dict(
    type="MultiModalDataset",
    dataset=dict(
        type="WeCocoDataset",
        data_root=gqa_data_root,
        ann_file=os.path.join(converted_root, "gqa_train_coco_xyxy.json"),
        data_prefix=dict(img="images/"),
        metainfo=dict(classes=gqa_classes_path),
        filter_cfg=dict(filter_empty_gt=False, min_size=32),
    ),
    class_text_path=gqa_class_text_path,
    pipeline=_base_.train_pipeline,
)

train_dataloader = dict(
    _delete_=True,
    num_workers=2,
    persistent_workers=_base_.persistent_workers,
    batch_size=_base_.train_batch_size_per_gpu,
    collate_fn=dict(type="yolow_collate"),
    sampler=dict(type="DefaultSampler", shuffle=True),
    dataset=dict(
        type="WeConcatDataset",
        datasets=[o365_train_dataset, flickr_train_dataset, gqa_train_dataset],
        ignore_keys=["classes", "palette"],
    ),
)


# --------------------------
# Validation / Test dataset
# --------------------------
# Keep using COCO val by default, but fix ann path to be relative to data_root
# to avoid duplicated path like: data/coco/data/coco/annotations/...
val_dataloader = dict(
    _delete_=True,
    batch_size=1,
    num_workers=2,
    persistent_workers=True,
    pin_memory=True,
    drop_last=False,
    sampler=dict(type="DefaultSampler", shuffle=False),
    dataset=dict(
        type="MultiModalDataset",
        dataset=dict(
            type="WeCocoDataset",
            data_root=coco_val_data_root,
            test_mode=True,
            ann_file=coco_val_ann,
            data_prefix=dict(img="val2017"),
            batch_shapes_cfg=None,
        ),
        class_text_path=coco_val_class_text_path,
        pipeline=_base_.test_pipeline,
    ),
)

val_evaluator = dict(
    _delete_=True,
    type="CocoMetric",
    ann_file=os.path.join(coco_val_data_root, coco_val_ann),
    metric="bbox",
)

test_dataloader = val_dataloader
test_evaluator = val_evaluator
